# Generated by Django 3.1.3 on 2021-03-02 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_auto_20210302_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='subirCancion',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
