# Generated by Django 3.1.3 on 2021-03-04 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musica', '0006_auto_20210304_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cancion',
            field=models.ManyToManyField(to='musica.Cancion'),
        ),
    ]
