# Generated by Django 3.1.3 on 2021-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0007_auto_20210304_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='subirCancion',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
