# Generated by Django 3.1.3 on 2021-03-11 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musica', '0008_auto_20210305_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
