# Generated by Django 3.1.3 on 2021-03-16 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0010_autor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='portada',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
