# Generated by Django 3.1.3 on 2021-03-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0011_album_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='caratula',
        ),
        migrations.AlterField(
            model_name='album',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
