# Generated by Django 3.1.7 on 2021-03-16 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0012_auto_20210316_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
