# Generated by Django 3.1.7 on 2021-03-19 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0013_autor_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='photo_playlist',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
