# Generated by Django 3.1.7 on 2021-03-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0014_playlist_photo_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='fecha_lanzamineto',
            new_name='año_lanzamineto',
        ),
    ]
