# Generated by Django 3.1.7 on 2021-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0016_auto_20210319_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='photo_playlist',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
